name: Build Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'vmc/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [apriltag_module, flight_control_module, mavp2p, peripheral_control_module, vio_control_module]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Docker Layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ hashFiles('**/Dockerfile') }}-${{ matrix.image }}
        restore-keys: |
          buildx-${{ hashFiles('**/Dockerfile') }}
          buildx

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
      with:
        version: latest
        install: true

    - name: Github CR Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUBCR_USERNAME }}
        password: ${{ secrets.GITHUBCR_PASSWORD }}

    - name: Build Docker Image
      run: docker build --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" -t ghcr.io/bellflight/vrc_${{ matrix.image }}:latest vmc/${{ matrix.image }}
  
    - name: Push Docker Image
      run: docker push ghcr.io/bellflight/vrc_${{ matrix.image }}:latest

